# Example configuration for Document Chat

# Optional HTTP/HTTPS proxy URL, e.g. "http://localhost:7890"
proxy_url = ""

# Override OpenAI base URL (leave empty for default)
openai_base_url = ""

# OpenAI API key; you can also set OPENAI_API_KEY env var
openai_api_key = ""

# Disable SSL verification for HTTP client (use only for trusted setups)
disable_ssl = false

# App mode (only 'chat' is supported)
mode = "chat"

# Assistant model name
model_name = "gpt-4o-mini"

# Embedding model (reserved / may be ignored by current SDKs)
# Common values: "text-embedding-3-small" (cheap), "text-embedding-3-large" (high quality)
embedding_model_name = "text-embedding-3-small"
